### ISSUE TITLE
There is an error after upadting Microsoft.Azure.DocumentDB.Core furthter than 1.9.1 

### ISSUE THREAD

**Issue by vindemi** [FelschR/AspNetCore.Identity.DocumentDB#37]
While trying to register new user using this:
`var result = await _userManager.CreateAsync(user, password);`

I get this error:

`Method not found: 'System.Threading.Tasks.Task1<Microsoft.Azure.Documents.Client.ResourceResponse1<Microsoft.Azure.Documents.Document>> Microsoft.Azure.Documents.Client.DocumentClient.CreateDocumentAsync(System.String, System.Object, Microsoft.Azure.Documents.Client.RequestOptions, Boolean)'.`

It happens when Microsoft.Azure.DocumentDB.Core library is updated into 2.0.0 +

**Comment by FelschR** [comment]
I've noticed this issue right when DocumentDB.Core 2.0 was released but I haven't found a solution yet.
I wasn't sure if it was perhaps a bug in the SDK itself but it's been out for a while now and I guess I should look into this again.

**Comment by yuramag** [comment]
Unfortunately, this is showstopper at the moment. I am voting +1 for the fix!

**Comment by FelschR** [comment]
The issue is that DocumentDB SDK 2.0 added new CancellationToken arguments to various methods which isn't backwards compatible.

The fastest fix would be to remove compatibility with < 2.0 versions.

Since our 2.0 beta release also has breaking changes I think there's no reason to make sure older DocumentDB SDK versions are supported.

I'll publish a new beta release today with DocumentDB SDK 2.0 compatibility but bear in mind that this beta is not compatible with v1.0 datasets of this library.
There is also some missing functionality with the new partitioning support.

For more information of the changes in the beta you can read the change logs here:
[2.0.0-beta](https://www.nuget.org/packages/AspNetCore.Identity.DocumentDB/2.0.0-beta2)
[2.0.0-beta2](https://www.nuget.org/packages/AspNetCore.Identity.DocumentDB/2.0.0-beta)

**Comment by FelschR** [comment]
https://www.nuget.org/packages/AspNetCore.Identity.DocumentDB/2.0.0-beta3
